### ISSUE TITLE
As a consumer of the ODH Mobility API, I want to get protected information

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-core#104]
**UPDATE 2020-02-10**
- [x] Use keycloak in BDP v1 @mmalfertheiner is working on it
> This has been cancelled, in favor of deprecation of V1 and usage of V2 inside bz-analytics, which is the only tool which needs a login
- [x] Use keycloak in BDP v2 Ninja @Piiit 
- [x] Write documentation on how to authenticate and how to configure a potential consumer
> Done by Aboutbits already, we just need to give credentials to externals, such that, they can access to our keycloak test server

**OUTDATED INVALID TODOS (for reference only)**
- [x] We need to discuss this within our group + Aboutbits (the Oauth server will then be outsourced)
- [x] After the completion of that project, a new authentication flow will be implemented for Ninja
- [x] ... and BDP v1
- [x] Add a Bearer Token (JWT) that contains all needed information from our general Oauth Identity Server (https://auth.testingmachine.eu/) to get protected data
- [x] Verify the JWT with a public key (taken from https://auth.testingmachine.eu/.well-known/openid-configuration/jwks x5c field)
- [x] Check also audience, scope and issuer
- [x] Extract BDP_ROLES and apply them on each REST call

**Comment by Piiit** [comment]
This works now, but I have a hardcoded barrier to only show open data, since our oauth server is still beta.

**Comment by Piiit** [comment]
@RudiThoeni Please test with Postman or curl, the current swagger does not support it yet

**Comment by RudiThoeni** [comment]
i geat a timeout on this calls
https://tomcatsec.testingmachine.eu/ninja/api/v2/flat/VMS,ParkingStation/*?select=mvalue
https://tomcatsec.testingmachine.eu/ninja/api/v2/flat/VMS,ParkingStation/*/2019-01-01/2019-01-02?select=mvalue

**Comment by Piiit** [comment]
@bertolla I added new flight rules about oauth https://github.com/noi-techpark/documentation/blob/master/FLIGHTRULES.md#oauth, just use the https://auth.testingmachine.eu address instead.

**Comment by bertolla** [comment]
@Piiit 
OK testing it like this worked(to get the token), but using ninja to get closed data did not really work. When the token expired I got "Internal Server Error 500"
```
 curl -i -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNCM0I2RUZCRkVCNzA1RjU4NEQ0M0ZBNkMxNEFEQTRBMEM5QjdERDkiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJPenR1LV82M0JmV0UxRC1td1VyYVNneWJmZGsifQ.eyJuYmYiOjE1NjgzNzcyOTMsImV4cCI6MTU2ODM4MDg5MywiaXNzIjoiaHR0cHM6Ly9hdXRoLnRlc3RpbmdtYWNoaW5lLmV1IiwiYXVkIjpbImh0dHBzOi8vYXV0aC50ZXN0aW5nbWFjaGluZS5ldS9yZXNvdXJjZXMiLCJhcGkxIl0sImNsaWVudF9pZCI6InVzZXIiLCJzdWIiOiI4IiwiYXV0aF90aW1lIjoxNTY4Mzc3MjkzLCJpZHAiOiJsb2NhbCIsInVzZXJuYW1lIjoiUGF0cmljayBCZXJ0b2xsYSIsImVtYWlsIjoicC5iZXJ0b2xsYUBub2kuYnouaXQiLCJyb2xlIjoiQkRQX0FETUlOIiwic2NvcGUiOlsiYXBpMSJdLCJhbXIiOlsicHdkIl19.c_HmCi0ZKWkC5j0gDjXrTDPlFrXH8l9aIOeFv0YLprVMZ9yj99iDzb3XqkDWyAWQJhGBK3epUEHRHifRcHXND5pllyeQ57ztbKc61cyTlA_3PDxTYl_6PrAXsiRU90lMqstPUs2nWBgr1epqwqCBtece8klSUzIf--FOxZS3q00Z7iitz4AhFAgEIvKSn8U-UW1kOBU8AytT14PYtbnO0kCQUbvKr_GxBJ0YYy-rwW4KhAEkzasi5dUgllBIMzotO_hbWUHnGppWeSbyjht5U1O_GYTg2Z7JGvWTdDyPSCsUyf-C3Gn-nutZ0sIz6OsDBg6jyCckbl6nBfvHxQZ1uA' "http://tomcat.testingmachine.eu/ninja/api/v2/flat/VMS/*"
```
and the resukt was:
```
{"timestamp":"2019-09-16T15:57:29.893+0000","status":500,"error":"Internal Server Error","message":"The Token has expired on Fri Sep 13 13:21:33 UTC 2019.","path":"/ninja/api/v2/flat/VMS/*"}patrick@patrick-Thinkpatrick@patrick-ThinkPad-T470s ~/git $ curl -i -X POST -H 'application/x-www-form-urlencoded' -d 'grant_type=password&username=p.bertolla%40noi.bz.it&password=abc&client_id=user&client_secret=secret' "https://auth.testingmachine.eu/connect/token"

```
and if the token worked I got
```
{"timestamp":"2019-09-16T15:59:39.727+0000","status":500,"error":"Internal Server Error","message":"No message available","path":"/ninja/api/v2/flat/VMS/*"}
```

**Comment by RudiThoeni** [comment]
we got an offer for externalizing the oauth server, to discuss in this sprint

**Comment by RudiThoeni** [comment]
moving back to EPICS because we are hiring Alex Lanz and Martin Malfertheiner to set up a OAuth Server

**Comment by Piiit** [comment]
@rcavaliere @bertolla The API v2 works now with keycloak on testing... please test as follows:
1) get a token from keycloak (access-token)
```http
POST https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username=your-keycloak-name
&password=your-keycloak-password
&client_id=odh-mobility-v2
```
--> optional test: copy/paste the token into https://jwt.io/ to see what it contains

2) get closed data from the API
```http
GET https://tomcatsec.testingmachine.eu/v2/api/flat/VMS/*?select=sname,mvalue
content-type: application/json
Authorization: bearer eyJhbGciOiJSUzI1............
```

**Comment by bertolla** [comment]
I worked with curl to do this
## retrieve auth token:
### ...url encoded
curl -L -H 'Content-Type:application/x-www-form-urlencoded' -X POST "https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token" -d 'grant_type=password&username=***&password=****&client_id=odh-mobility-v2'
and i got a token

### ... json encoded
I also tried to do it with json but didn't work:
`curl -L -H 'Content-Type:application/json' -X POST "https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token" -d '{"grant_type":"password","username":"***","password":"*******","client_id":"odh-mobility-v2"}'`

## retrieve data with token
tried the token which I got from auth server and first thing i noticed is you use **bearer** instead of **Bearer** in the auth string. I think the second one is standard https://tools.ietf.org/html/rfc6750

I didn't get any data back any data anyway and no error msg. Is it because my user has not the permissions?
How are the users mapped between bdp and v2?

**Comment by bertolla** [comment]
I also tried to get another access token through refresh token in kc and it worked like a wonder:
curl -L -H 'Content-Type:application/x-www-form-urlencoded' -X POST "https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token" -d 'grant_type=refresh_token&refresh_token=*****&client_id=odh-mobility-v2'

**Comment by rcavaliere** [comment]
I am trying to test this but I am not able to get a token before accessing the closed data.
I get as a response with CURL:
{"error":"invalid_grant","error_description":"Invalid user credentials"}
Any idea on what I am doing wrong?

**Comment by Piiit** [comment]
@rcavaliere Could you pleas try to access https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/auth?client_id=account and see if you can set your password, and then retry?

**Comment by rcavaliere** [comment]
@Piiit I see an end-point with the possibility to log-in with username / password, how should I proceed?

**Comment by Piiit** [comment]
@bertolla it does not matter if you use `bearer` or `Bearer`. Both work. I think you get the internal server error while retrieving closed data, because you used the production API... could that be possible?

@bertolla @rcavaliere 
I wrote a flightrule now, please test if it is good enough.
https://github.com/noi-techpark/documentation/blob/master/FLIGHTRULES.md#i-want-to-retrieve-closed-data-in-v2

**Comment by Piiit** [comment]
@bertolla You do not have the permissions to retrieve closed data. I added that role now to your user inside keycloak

**Comment by bertolla** [comment]
ok I tried it with vms and it works!!
