### ISSUE TITLE
As a project manager, I would like to ask credentials for Davide Montesin and Chris Mair in order to access all data of the ODH

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#108]
Otherwise during the development phase of analytics.mobility.bz.it they can not test if all data are correctly visualized.

- [x] Davide
- [x] Thomas
- [x] Chris

**Comment by bertolla** [comment]
With Davide and Thomas we need to find a secure way to pass credentials.

**Comment by rcavaliere** [comment]
Can't you use the Outlook system you used with me?

**Comment by bertolla** [comment]
No, that only works wit office365

**Comment by bertolla** [comment]
Normaly we would use PGP. Alternatives are Nextcloud via Phone or picking it up personally

**Comment by rcavaliere** [comment]
@bertolla how should I test this :-) ?? Let's put this story directly in DONE if you gave them their credentials...

**Comment by bertolla** [comment]
Theoretically the 3 ppl need to check if access works. Since i got no feedback I guess it's fine like this
