### ISSUE TITLE
As a traffic expert, I would like to have new link stations in the Open Data Hub

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#112]
Following links have to be created:
- [x] siemens -> proma
- [x] proma -> druso-poste
- [x] druso-poste -> proma

**Comment by Piiit** [comment]
@rcavaliere Done. Please test

**Comment by Piiit** [comment]
@rcavaliere @bertolla 
I created also a flight rule for future inserts: https://github.com/noi-techpark/documentation/blob/master/FLIGHTRULES.md#i-want-to-create-links-between-stations

**Comment by bertolla** [comment]
Documentation seems to be good to me

**Comment by rcavaliere** [comment]
@Piiit nice work! Let's close this issue.
