### ISSUE TITLE
As a traffic expert I would like to create new Link Stations due to the installations of new Bluetooth boxes in the city of Bolzano

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#116]
- [x] `LinkStation` must be visible as web service for the API v1 @Piiit 
> Done, https://ipchannels.integreen-life.bz.it/origin-destination
- [x] Add a spreadsheet with link stations, that will be read from the data collector of bluetooth stations @bertolla 
> duplicate of #117
- [x] Add all link stations with coordinates to that spreadsheet @rcavaliere 
- [x] Verify that all new LinkStation geometries are stored correctly in the production environment (should be automatic) @rcavaliere @bertolla 
- [x] Delete geometry of LinkStations "proma->druso-poste" and "siemens->proma" @bertolla 
- [x] @rcavaliere Should I also delete geometries inside `smetadata` of edge stations? YES --> done, see comment below for query

@rcavaliere @bertolla I updated the to do list of this issue, hope it is correct like this.

**Comment by bertolla** [comment]
This issue depends on noi-techpark/bdp-core#117 and the second checkbox is exactly that

**Comment by Piiit** [comment]
@bertolla I updated the to do list above

**Comment by rcavaliere** [comment]
Hi where can I find all documentation done by Peter for creating new Link Stations?

**Comment by Piiit** [comment]
@rcavaliere It is in our flightrules: https://github.com/noi-techpark/documentation/blob/master/FLIGHTRULES.md#open-data-hub-mobility

**Comment by rcavaliere** [comment]
I created a new LinkStation following the documentation: Maso_Pieve->meinstein
Let's see if the elaborations are automatically computed.
I have also created with QGIS the correspondent line geometry, available here: https://cloud.opendatahub.bz.it/index.php/s/QEx45FzwrNWHEbf
@bertolla can you assign the geometry to this new LinkStation in the DB?
If everything is fine I will start to populate the DB with all new LinkStations and create the correspondent geometries. In total we will have nearly 40 LinkStations! But this will go quite fast with the procedure that we have put in place.

**Comment by rcavaliere** [comment]
Created all new LinkStations. Now I will create the correspondent geometries

**Comment by rcavaliere** [comment]
I need the new laptop to complete this user story, which I don't have with me at home. I suggest to postpone it when the emergency is finished...

**Comment by bertolla** [comment]
@rcavaliere to update the links just deposit the shapefile in the folder links in this repository:
https://github.com/noi-techpark/bdp-elaborations/tree/master/ShapefileFeatureImporter

**Comment by rcavaliere** [comment]
@bertolla I have uploaded all geometries of the LinkStations related to this user story, as defined in your comment above: https://github.com/noi-techpark/bdp-elaborations/commit/cb6614cff3bd91a44cb1416ac3fcd2b76bdd6a70
I have inserted a new task in the user story since I would like to delete some existing geometries related to other LinkStations, since we have now much more BluetoothStations and we consider shorter paths for the travel times computation

**Comment by Piiit** [comment]
@bertolla I will perform a manual data manipulation as follows:

```sql
with src as (
	select m.station_id, now(), m.json - 'coordinates' - 'length' - 'street_ids_ref' - 'destination' - 'elapsed_time_default' 
	from station s 
	join intimev2.metadata m on m.station_id = s.id 
	where s.stationtype = 'LinkStation'
	and json ? 'coordinates'
),
ins as (
	insert into metadata (station_id, created_on, json) 
	select * from src
	returning id, station_id
)
update station s set meta_data_id = ins.id from ins where s.id = ins.station_id
```
