### ISSUE TITLE
As a traffic expert I would like to assign the positions to the new Bluetooth boxes, so that they are visible on the analytics webapp

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#117]

**Comment by bertolla** [comment]
My suggestion would be that the datacollector itself takes the data from a spreadsheet and does the correlation and sends the complete dataset to odh

**Comment by rcavaliere** [comment]
Can you do this during this sprint? I have already the coordinates of the new boxes. Please create and share with me the spreadsheet so that I can integrate this info

**Comment by bertolla** [comment]
@rcavaliere 
You can test it now by changing the spreadsheet here
https://docs.google.com/spreadsheets/d/10qBMw28HFWJZen6_CBKT1ln5s8XdygcoC3buXas_8SA/edit#gid=0

Documentation can be found here: https://github.com/noi-techpark/bdp-commons/tree/development/data-collectors/vehicletraffic-bluetooth#user-content-metadata-through-google-spreadsheet

To see the results check the test database.

**Comment by rcavaliere** [comment]
Inserted coordinates of all active Bluetooth sensors. Please go in production
