### ISSUE TITLE
As a traffic analyst, I have an issue regarding a wrong name of a Bluetooth box

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#118]
CISMA has given the stationcode "Arginale_Roma" to a new box, but this is wrong and it will be renamed this week with "Galleria_Virgolo".
Data with the old stationcode are already entering. What do you suggest to do in order to avoid to have two stations in the DB? Can we assign all current measurements to the the station "Galleria_Virgolo" and then delete the station "Arginale_Roma"? How do you suggest to handle this issue?

**Comment by bertolla** [comment]
Two ways:
- if the change will be done in a short time and not a lot of data comes in: 
  - update reference of measurement,measurementhistory,measurementstring, measurementstringhistory to the new automatically created station (Galleria_Virgolo)
  - delete old station(Arginale_Roma) and all referencing data(metadata,bdprules,bdppermissions)
- if the change will longer and a lot of data is accumulated:
  - rename 'Galleria_Virgolo' to 'temp' in between 5 minutes gab to avoid recreation of station
  - rename 'Arginale_Roma' to the new station in between 5 minutes gab to avoid recreation of station
  - do the same steps as in solution one but for 'temp' station

**Comment by rcavaliere** [comment]
I suggest way 1, this is what I thought to do.

**Comment by bertolla** [comment]
OK we will try to do that as soon as you tell us about the change.

**Comment by rcavaliere** [comment]
We can proceed now. The name change was completed by CISMA

**Comment by bertolla** [comment]
Please check on the analytics tool / db if everything works as expected
