### ISSUE TITLE
As a traffic analyst, I would like to understand the issue with the latest A22 traffic calculations

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#122]
Strange data since 15.11 ca.

**Comment by bertolla** [comment]
- a22 data was missing from 14.November
- datacollector invented faulty data after that time

**Comment by rcavaliere** [comment]
So what are the next steps?

**Comment by bertolla** [comment]
@rcavaliere 
- [x] A22 bulk import
- [x] restart follow mode for A22 connector
- [x] delete wrong elaborations
- [ ] recalculate elaborations(in progress)

**Comment by rcavaliere** [comment]
Very well! Let's keep this open for a while until we are again aligned with the real-time elaborations
