### ISSUE TITLE
As a traffic analyst, I would like to have all current elaborations applied to Bluetooth and Link Stations with period = 600 and period = 3600

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#123]

**Comment by bertolla** [comment]
Elaboations countMatches/countVehicles where/are made and should be available in the production db

**Comment by rcavaliere** [comment]
Wonderful work @bertolla, it seems that everything works very well!

**Comment by rcavaliere** [comment]
@bertolla made some deeper testing, it seems to work very well for all boxes, but for some strange reasons the elaborations with these new periods are not visible for Agip_Einstein. Can you please check this?

**Comment by bertolla** [comment]
Data has been calculated and inserted in the history table but form some reason it's missing in the measurement table

**Comment by rcavaliere** [comment]
Now I can see the new elaborations for Agip_Einstein. I just realized however that are missing the elaboration "Bluetooth Elapsed time (test) " with the new period = 600. Can you include this task as well please?

**Comment by bertolla** [comment]
The task is called run_mode_intime and is currently running for the new period 600, see http://34.242.151.129/bluetoothtrafficelaboration/

**Comment by rcavaliere** [comment]
Wonderful! Please also add the computation compute_bspeed with period = 600, otherwise we don't get the final computation available on the average speed. Thanks!

**Comment by bertolla** [comment]
I inserted the task but it won't work as long as geometries are missing and elaborations get adapted.

**Comment by bertolla** [comment]
updated compute speed sql and should now create elaborations for that too.

**Comment by rcavaliere** [comment]
@bertolla, elaborations are present but there is something which is not working properly, see elaborations example here. In many cases the values are reasonable but there are lot of situations in which speed computations have very high negative values. Is this related to the geometries? What are the lengths of the links that are used in the calculation?
![Bug](https://user-images.githubusercontent.com/9825179/73117093-e9220880-3f40-11ea-9f6b-b071bb4710ba.png)

**Comment by bertolla** [comment]
At the moment these are the active link stations and the length used for calculation:
 Galilei_Palermo->Galilei_Lancia | 356.127215524399
 siemens->Galilei_Palermo        | 453.726632482723
 Torricelli->siemens             | 526.123805964823
 Agip_Einstein->Torricelli       | 1146.52010542181
 meinstein->Maso_Pieve           | 1493.43646174418
 Maso_Pieve->meinstein           | 1493.43646174418
 A22_ML103->Torricelli           | 19168.0624133768

**Comment by bertolla** [comment]
These are the changes made:
https://github.com/noi-techpark/BluetoothTrafficElaboration/commit/3758161cee84d2f61b1bd7da38d81444db57eb50

**Comment by bertolla** [comment]
I guess the negative values are some sort of error message which Davide defined(it's always the same negative value). For the specific case I checked some data and since count matches for those links is always 0 it also means that speed calculations make no sense.

**Comment by rcavaliere** [comment]
This will be fixed by Davide Montesin with a modification of the elaboration chain. In case of no data, no elaboration will be computed (at the moment a default value is set, but this make plot unreadable)

**Comment by rcavaliere** [comment]
There is an open pull request by Davide fixing this, @bertolla please integrate it in the testing environment so that we can check if this work as expected. Which is the version of the analytics which visualizes the data in the testing environment? Is http://tomcat.testingmachine.eu/analytics/?
