### ISSUE TITLE
Fix JSON selector regression introduced by the function support commits

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-core#125]

**Comment by Piiit** [comment]
@bertolla Please test under https://tomcatsec.testingmachine.eu/v2

Test if JSON selection works. That is, see if you can use "something.something" (with one or more dots in between) in "select".

Test if functions work, like "count(mvalue)" or "avg(mvalue)" or similar things... It does not work with JSON yet, so "count(smetadata.something)" will not work.

**Comment by bertolla** [comment]
Tried this query:
`https://tomcatsec.testingmachine.eu/v2/api/flat/EChargingPlug?limit=-1&offset=0&select=smetadata.outlets&where=sactive.eq.true&shownull=false&distinct=true`
which failed beforehand and it seems to work correctly
