### ISSUE TITLE
As a parking data consumer, I would like to have also the data type "free" availability, so that the visualization of this information in end-user apps can be more easily implemented

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#126]
A new data type should be generated. The elaboration should just compute the difference between the metadata "capacity" and the other available data type "occupacy"

**Comment by bertolla** [comment]
Sorry, but I'm against it. It would mean double the data volume with close to no benefit.
By using the new ninja API it's really simple to get the historical data and the capacity with one simple call. Furthermore the calculation on a javascript frontend costs close to nothing.
What are the arguments for it?
 Maybee @Piiit and @RudiThoeni   can also give their opinion about this.

**Comment by rcavaliere** [comment]
With the current API retrieving the free data is not immediate, but you are right if with APIv2 this is quick and simple this is not necessary. Let's make a try like that.
