### ISSUE TITLE
As a VMS data consumer, I would like to associate to the pictrograms codes their meaning, in a text form, so that the visualization of this information in end-user apps can be more easily

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#127]
A simple elaboration should convert the following value numbers with their significance, according the attached look-up table. Not only the data type "esposizione" has to be affected, only in the cases value numbers are stored, but also the direction type and VMS type (metadata) should be translated. Additional values could be generated so to maintain this raw data in the metadata and in the measurementstring / measuremenstringthistory tables.
[ALLEGATO1_CodiciConversione.pdf](https://github.com/noi-techpark/bdp-core/files/4087892/ALLEGATO1_CodiciConversione.pdf)

**Comment by bertolla** [comment]
@rcavaliere 
Is this file also available as csv or any other format? Where can I find the newest version?

**Comment by rcavaliere** [comment]
@bertolla unfortunately we just have a PDF file... see attached
[ALLEGATO1_CodiciConversione.pdf](https://github.com/noi-techpark/bdp-core/files/4180096/ALLEGATO1_CodiciConversione.pdf)

**Comment by bertolla** [comment]
And ask this softtech if they can provide a usable format? If not, somebody has to copy and paste each line.

**Comment by bertolla** [comment]
After various discussion a way was found to handle this case, but can also be used in lots of other circumstances. This changes are reflected in the new schema 4.0.0 and are documented in the source code.
Now every datatype can have multiple datatype associated, as stations already do.

**Comment by bertolla** [comment]
The following have to be implemente to make this work:
- [x] change schema and datastructure of bdp-core
- [x] change datacollector so it sends metadata of types
- [x] adapt datacollector, so it parses metadata from csv file
- [ ] change Ninja so it exposes metadata of datatypes @Piiit

**Comment by Piiit** [comment]
@bertolla @rcavaliere OK, I take this now into my Sprint To Do... maybe next sprint thou

**Comment by Piiit** [comment]
@bertolla @rcavaliere Done, it is only on testing

https://tomcatsec.testingmachine.eu/v2/swagger-ui.html

Please check.

**Comment by bertolla** [comment]
ok I tried it out and it seems like ninja on testserver exposed vms data but only when I put it as open data. Which means authentication will be required when accessing this data.
This is an example on how to retrieve typemetadata of vms when it is open data:
```
curl -X GET "http://tomcat.testingmachine.eu/v2/api/flat/VMS/*?limit=200&offset=0&shownull=false&distinct=true&select=tname,tmetadata" -H "accept: application/json"
```

**Comment by bertolla** [comment]
This issue noi-techpark/bdp-core/issues/104 should also resolve the authentication issue and you should use the auth token to do the request so you can get all results:
`curl -H 'Authorization:Bearer <tokenstring>' -X GET "http://tomcat.testingmachine.eu/v2/api/flat/VMS/*?limit=200&offset=0&shownull=false&distinct=true&select=tname,tmetadata" -H "accept: application/json"
`

**Comment by bertolla** [comment]
It works now. @rcavaliere Can you test it with your keycloak account so we can move it to put in production??

**Comment by rcavaliere** [comment]
I will do it, but I am busy at the moment with hard deadlines. I am confident to make it by the end of the week.

**Comment by rcavaliere** [comment]
@Piiit @bertolla Can we put this in production, so that we can see this improved information associated to VMS and we can get it visible on analytics?

**Comment by Piiit** [comment]
@rcavaliere Ok. Let us see later. We need to add all BDP roles to our production keycloak, otherwise it will not work and you need also a production account... however, I open it again. Otherwise, it cannot be put into right column on our Kanban... Closing an user story moves it to the DONE column automatically...

**Comment by Piiit** [comment]
@bertolla Who should do this?

**Comment by bertolla** [comment]
@rcavaliere 
For future issues you want to be deployed to production after testing please do the following steps.
- move issue to release on production lane
- assign the person who should do it(mostly the person/s who worked on it)

~~closing issues~~ ... moves to sprint done and we devs ignore it

**Comment by Piiit** [comment]
@bertolla @rcavaliere 
This works now on production... To test it see this flightrule

https://github.com/noi-techpark/documentation/blob/master/FLIGHTRULES.md#i-want-to-retrieve-closed-data-in-v2

**Comment by rcavaliere** [comment]
@Piiit if it is now in production, this information should be available also through API v1, isn't it? Therefore analytics app should now visualize the meaning of the pictograms codes. But I don't see this information... do you have an explanation for that?

**Comment by Piiit** [comment]
@rcavaliere About API v1 I have no idea. We have it inside the DB and V2 exposes them. Maybe @bertolla can tell you more about V1... that part was done by him.
