### ISSUE TITLE
As a user I would like to see the improved Bluetooth elaborations in production (no data -> no elaborations, high-speed vehicles dedicated elaboration)

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#135]
Accept PR for
- bug: when no data no calculation
- average should be by category (light vehicles)

**Comment by bertolla** [comment]
I think I deployed the changes by Davide alreadon on Feb 25th. I will redeploy everything to be sure.

**Comment by bertolla** [comment]
@rcavaliere 
Can you check in the production db and on http://99.81.104.41/bluetoothtrafficelaboration/ if the changes are actually affecting the data. I think they are. I checked on https://analytics.mobility.bz.it and it seem to be correct but for some linkstations data seems to be missing. Am I right?

**Comment by rcavaliere** [comment]
@bertolla thanks! I confirm, now the elaborations are computed in the right way. In some cases elaborations are missing because geometries are missing. This is related to issue https://github.com/noi-techpark/bdp-core/issues/116
Now Davide needs to implement a new elaboration related to the LinkStations. He needs two additional data types:
- [ ] Bluetooth Elapsed time (test) greater than 100 km/h
- [ ] velocita' greater than 100 km/h
Can you please manage with him this request? The reference mail request of Davide has subject **elaboration type_id per moda e velocità > 100 km**

**Comment by bertolla** [comment]
@rcavaliere 

1. Is there a logical reason why we need a new datatype for the same kind of data, just faster? Can't we use the same?
2. If we create this one can't we use better naming: like `Bluetooth Elapsed time greater than 100 km/h`  and `speed  greater than 100 km/h` ?

**Comment by rcavaliere** [comment]
@bertolla yes, because the elaborations are different from the other ones, therefore new data types are necessary. It's OK to give the names you propose. Is it possible to update the naming of all Bluetooth elaborations, so that they are homogeneous and all in English?

**Comment by bertolla** [comment]
Ok, the only thing is that I can't give Davide the same  for test and prod, since those are autogenerated values and vary between the 2 systems.

**Comment by bertolla** [comment]
> Is it possible to update the naming of all Bluetooth elaborations, so that they are homogeneous and all in English?
I think we should open a new userstory for this since it's not as simple as it seems.

**Comment by rcavaliere** [comment]
Ok, in the meantime can we concentrate on the generation of the new data types?

**Comment by bertolla** [comment]
Already done it. I will mail it to Davide

**Comment by rcavaliere** [comment]
@bertolla how is the situation here? I see the new data types in the test DB (I can able to access from home, by adding a rule on AWS security groups), but no elaboration flowing in. Are we still waiting Davide to finish his work?

**Comment by rcavaliere** [comment]
@bertolla sure to have made the PR with the fix of Davide?
If I query select * from intimev2.measurement where type_id = 5968 or type_id = 5969 I don't get any data (while data is available in the measurementhistory table...)

**Comment by bertolla** [comment]
@rcavaliere 
http://99.81.104.41/bluetoothtrafficelaboration/
and check data in production db
Cheers

**Comment by rcavaliere** [comment]
@bertolla many thanks, it works very well! Interesting comparisons now possible on the highway patterns, e.g.: [link](https://analytics.mobility.bz.it/#%7B%22active_tab%22:0,%22height%22:%22400px%22,%22auto_refresh%22:false,%22scale%22:%7B%22from%22:1582585200000,%22to%22:1582930800000%7D,%22graphs%22:%5B%7B%22category%22:%22Vehicular%20Travel%20Time%22,%22station%22:%22A22_ML103-%3ETorricelli%22,%22station_name%22:%22A22_ML103-%3ETorricelli%22,%22data_type%22:%22Bluetooth%20Elapsed%20time%20greater%20than%20100%20km/h%22,%22unit%22:%22ms%22,%22period%22:%22600%22,%22yaxis%22:1,%22color%22:0%7D,%7B%22category%22:%22Vehicular%20Travel%20Time%22,%22station%22:%22A22_ML103-%3ETorricelli%22,%22station_name%22:%22A22_ML103-%3ETorricelli%22,%22data_type%22:%22Bluetooth%20Elapsed%20time%20(test)%22,%22unit%22:%22%22,%22period%22:%22600%22,%22yaxis%22:1,%22color%22:1%7D,%7B%22category%22:%22Vehicular%20Travel%20Time%22,%22station%22:%22A22_ML103-%3ETorricelli%22,%22station_name%22:%22A22_ML103-%3ETorricelli%22,%22data_type%22:%22speed%20greater%20than%20100%20km/h%22,%22unit%22:%22km/h%22,%22period%22:%22600%22,%22yaxis%22:2,%22color%22:2%7D,%7B%22category%22:%22Vehicular%20Travel%20Time%22,%22station%22:%22A22_ML103-%3ETorricelli%22,%22station_name%22:%22A22_ML103-%3ETorricelli%22,%22data_type%22:%22velocita'%22,%22unit%22:%22km/h%22,%22period%22:%22600%22,%22yaxis%22:2,%22color%22:3%7D%5D%7D)
