### ISSUE TITLE
Synchronisation of stations fails if a different stationtype is provided in the sync station call

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/bdp-core#137]
As described by T.Nocker our writer might have a bug
> ho notato un bug (credo?) in datacollector: Se chiamo la funzione
syncStations e passo anche un datasourceName, vengono settati tutti le
stazioni del database come active = false che hanno lo stetto origin,
anche se il datasourceName é diverson. Credo che sia un bug, perché la
chiamata fetchStation al contrario tona solo le stazioni che hanno il
datasourceName indicato.

**Comment by Piiit** [comment]
Fixed
