### ISSUE TITLE
As a consumer of the Ninja API, I want to know that functions can only be used with "flat" representations and have the API also tell me that as error response

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-core#140]
The API should tell me that "min", "max" etc. cannot be used with "tree" representations.
Update the README accordingly

Related to https://issues.opendatahub.bz.it/Ticket/Display.html?id=453

**Comment by Piiit** [comment]
@stefanodavid FYI

**Comment by stefanodavid** [comment]
Great timing... I was exactly working on these functions

**Comment by Piiit** [comment]
@stefanodavid The new version supports now "tree" + functions, it is on https://tomcatsec.testingmachine.eu/v2 and can be tested via https://swagger.opendatahub.testingmachine.eu/?url=https://tomcatsec.testingmachine.eu/v2/apispec

**Comment by Piiit** [comment]
@bertolla @rcavaliere Please test (see comment above)

**Comment by Piiit** [comment]
@rcavaliere As we agreed in our mail exchange, we can nou put this into production
