### ISSUE TITLE
Setup Jenkins for docker deployment of Ninja

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-core#157]
- [x] @mmalfertheiner Test environment
- [x] @Piiit production environment

**Comment by Piiit** [comment]
@bertolla http://prod-docker-ninja-285504032.eu-west-1.elb.amazonaws.com/ is the new production endpoint, just need to fix swagger and then we are ready to go...

Please test :-)

**Comment by bertolla** [comment]
What should I test of ninja? Just if it's up and running?

**Comment by Piiit** [comment]
@bertolla All other things seems to work, I will switch to the new instance today... if you agree

**Comment by bertolla** [comment]
imao you should first try to switch some applications which are running on test environments to this endpoint to avoid crashes in production

**Comment by Piiit** [comment]
@bertolla Ninja is finally on docker now, from local development, testing and production... 
Seems to be fine....

Thx @mmalfertheiner and @alexlanz for your great support!!!
