### ISSUE TITLE
Grafana: send notification emails as alarms based on conditions in the mobility dashboard

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/bdp-core#161]

**Comment by mmalfertheiner** [comment]
https://grafana.testingmachine.eu/d/Gt7fV-3Wk/mobility-alarms?orgId=1

**Comment by mmalfertheiner** [comment]
@bertolla I created a new dashboard. What do you think? https://grafana.testingmachine.eu/d/6836nBmMz/collector-overview?orgId=1

**Comment by bertolla** [comment]
Looks great, but how do you differentiate between what to show in green and what in red?
In the meantime Roberto C. asked me to create a second represenation where we group by station(and not by datatype). Maybe you noticed already: https://grafana.testingmachine.eu/d/oPg8qgZGz/mobility-alarms-by-station In this case we have even more points.

**Comment by mmalfertheiner** [comment]
This is the final version of the dashboard:

https://grafana.testingmachine.eu/d/fnfFHEZGz/mobility-collector-overview?orgId=1

**Comment by Piiit** [comment]
@bertolla Please review and move to done inside the Aboutbits Kanban if happy

**Comment by bertolla** [comment]
The dashboard is fine but we still get no mail notification when datacollectors are failing.
@rcavaliere can you confirm?

**Comment by rcavaliere** [comment]
@bertolla yes, I confirm

**Comment by bertolla** [comment]
Me and Martin tried to fix the current configured dashboard and alarming system. If it still does not work we will switch to another strategy of alarming through elasticsearch and a custom elaboration

**Comment by bertolla** [comment]
I got the notification, so it seems to be working now.

**Comment by rcavaliere** [comment]
But from this notification (OK) I don't understand what has been fixed....
![Screenshot from 2020-12-11 07-38-01](https://user-images.githubusercontent.com/9825179/101871464-e4c80380-3b83-11eb-9aa9-4461075b3886.png)
