### ISSUE TITLE
Investigate the outage of BDP Database 100% CPU load

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-core#163]
Related to ticket https://issues.opendatahub.bz.it/Ticket/Display.html?id=592&results=82d82ef5a8cf0e8cc02bcc460b66f0c4

**Comment by Piiit** [comment]
@bertolla @mrabans 

I've found 3 possible culprits (all related to Ninja - Mobility API v2):
1. Ninja queries the database without statement timeouts, that is if a query takes a long time and is costly, Postgres runs at 100% CPU for a long time
> solved in testing, there is a parameter now where we can set timeouts (at the moment it is set to 30 seconds)
2. Ninja queries the database and gets a huge response, then in the "tree" representation it builds a tree. This tree can consume so much memory, that the instance where Ninja runs gets out-of-memory. The main reason for this is "tmetadata" which gets copied over and over again into results, when the tree contains the same metadata for datatypes and those have base64 images, these are immediatley several 100x of MB.
> solved in testing, there is a parameter now where we can set a max MB for tree responses (at the moment 100MB). If exceeded, the user gets an error
3. Only on testing, our proxy apache2 timed out and those responded with a HTML page. The client does not understand xml documents, and those responds with an error 
> solved, I added a timeout to the apache2 config on our proxy. However, this will not be triggered since Ninja itself fails gracefully now and provides json errors before that happens. Nevertheless I kept this just to be sure.

**Comment by Piiit** [comment]
@rcavaliere @ohnewein FYI

**Comment by mrabans** [comment]
great result!
