### ISSUE TITLE
Metadatafilter not working with underscores

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/bdp-core#164]
See example:
https://mobility.api.opendatahub.bz.it/v2/flat/NOI-Place?limit=-1&offset=0&select=sname,smetadata&where=and(sactive.eq.true,smetadata.building%5fcode.eq.A4)&shownull=false&distinct=true

**Comment by Piiit** [comment]
This should be fixed now, try it with
https://mobility.api.opendatahub.testingmachine.eu/flat/NOI-Place?limit=-1&offset=0&select=sname,smetadata&where=and(sactive.eq.true,smetadata.building_code.eq.A4)&shownull=false&distinct=true

**Comment by Piiit** [comment]
A small hint about the WHERE clause:
```
where=and(sactive.eq.true,smetadata.building_code.eq.A4)
```
is the same as
```
where=sactive.eq.true,smetadata.building_code.eq.A4
```
because `and` is the default when not otherwise stated

**Comment by bertolla** [comment]
@Piiit 
I tested it,but it has become horribly slow. The query without the filter takes 100 ms on the prod environemnt and this endpoint need 3 seconds now. Is it the testing env or does the filter make it slow?
And yes I knew about the `and` stuff, I was just testing since the query failed I thought I had understood something wrong.

**Comment by Piiit** [comment]
@bertolla It is just the test environment, so no worry...

**Comment by Piiit** [comment]
@bertolla Do you need other special chars for names in targets? For example, `-` as in `smetadata.water-temperature`...

**Comment by bertolla** [comment]
I guess it would be better to escape all special characters, since we have no control on what lands in metadata tables

**Comment by Piiit** [comment]
@bertolla This issue already exists, so I will just release this one and then we can decide whether we want to add other special chars.

https://github.com/noi-techpark/bdp-core/issues/114
