### ISSUE TITLE
Ninja: mvalue missing in some queries

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-core#166]
https://mobility.api.opendatahub.testingmachine.eu/tree/MeteoStation/*/latest?select=sdatatypes&limit=1

https://mobility.api.opendatahub.testingmachine.eu/tree/MeteoStation/*/latest?select=tmeasurements&limit=1

It seems that it is not shown, when pointers to target definitions are used

https://mobility.api.opendatahub.testingmachine.eu/tree/MeteoStation/*/latest?select=sdatatypes,mvalue&limit=1
works

**Comment by Piiit** [comment]
@bertolla @noctho This should be fixed now, please test with the queries above and see if you get mvalue together with other values. To compare, query it with https://mobility.api.opendatahub.testingmachine.eu/tree/MeteoStation/*/latest?limit=1 and see if you get the same key/value pairs as in tmeasurements and sdatatypes.

**Comment by bertolla** [comment]
All queries work even on production so I guess this was already solved
