### ISSUE TITLE
As an APP developer I would like to get through the edge method of the ODH API also the geometries of the A22 LinkStations

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#174]
TODOS

- [x] @Piiit Adapt the schema that edges shouldn't have origin and destination mandatory, since some geometries are not connected to stations inside bdp-core/dal
- [x] @Piiit Allow API v2 to expose edges without origin and destination
- [ ] @rcavaliere Import new edge data and new geometries

-------
OLD COMMENT:

Still need to be created in the ODH core, will be available through the "edge" method as for the other LinkStations

**UPDATE BY @Piiit**
This means, that the edges shouldn't have origin and destination mandatory, since some geometries are not connected to stations.

I performed the following changes on prod and test:

```sql
ALTER TABLE intimev2.edge ALTER COLUMN edge_data_id SET NOT NULL;
ALTER TABLE intimev2.edge ALTER COLUMN destination_id DROP NOT NULL;
ALTER TABLE intimev2.edge ALTER COLUMN origin_id DROP NOT NULL;
```

This was done manually, we need Flyway for bdp-core... The issue for that is https://github.com/noi-techpark/bdp-core/issues/185

**Comment by rcavaliere** [comment]
First geometries have been created, but are not currently visible on the API. Next steps:
- [ ] @bertolla and @rcavaliere investigate and solve the issue
- [ ] @rcavaliere completes the work for all LinkStations

**Comment by Piiit** [comment]
@rcavaliere I would like to finalize this issue and the related one? Is this about the edges without start and ending stations?

**Comment by rcavaliere** [comment]
Yes. Origin and destination shouldn't be mandatory in the edge table since in some cases we don't have them as stations in the station table

**Comment by Piiit** [comment]
We have two possible solutions here:

1. Use stations directly and add a field for polyline geometries (API calls must then be made against nodes and not edges). This would involve a check and probably a change in the station data model (I told you otherwise yesterday, but after a check I've got some doubts if that would be that easy)

2. Create tangling edges, that is edges without origin and destination stations (this is the original idea we had), althout in mathematical terms this would not be an edge anymore if we look at graph theory, where edges are pairs of nodes.

Maybe we should think from the POV of our API consumers. I do not know yet, what they would like to have here, and what is easier to understand? Maybe just define points on a map as nodes and any (connected or not-connected) polygon as edge (in the sense of a multiline and less of graph edges).

What do you think?    @bertolla @rcavaliere

**Comment by rcavaliere** [comment]
@Piiit I would go in direction 2.
I agree, maybe the term "edge" is a little bit misleading if we mix up things.
Actually the LinkStations associated to BluetoothStations can be handled as "edge", whereas LinkStations that do not have such reference should be handled as simple polygons... Maybe the solution could be foresee a separate table, equivalent to edge, named "polygon", without origin and destination reference (only a reference to the LinkStation ID of station), in which we save the geometry of such LinkStations?

**Comment by Piiit** [comment]
@rcavaliere Please insert an edge without starting and ending stations, I hope it works ... I will test it also after the meetings today

**Comment by Piiit** [comment]
@rcavaliere I have created an example for you... query as follows:

```
https://mobility.api.opendatahub.testingmachine.eu/v2/flat,edge/*?where=sbactive.eq.null
```

**Comment by rcavaliere** [comment]
I had already added in my QGIS project a geometry of an A22 LinkStation: https://cloud.opendatahub.bz.it/index.php/s/zfGLREeJAKcWQng
I already uploaded it in the core according to https://github.com/noi-techpark/bdp-elaborations/tree/master/ShapefileFeatureImporter
Here my PR: https://github.com/noi-techpark/bdp-elaborations/commit/2bbcddb6693ded4f213b7016806c937384a2b9c1
Can you check with this?

**Comment by Piiit** [comment]
@rcavaliere I have written some flight rules for you. Now, I will put this into production, such that, we can try the shape importer with it... what do you think?

**Comment by rcavaliere** [comment]
Perfect!!

**Comment by Piiit** [comment]
@rcavaliere I've put all into production, please run your importer... Do you still need something from me?

**Comment by rcavaliere** [comment]
No, I will start with this activity, probably next week. Thanks!

**Comment by Piiit** [comment]
top!
