### ISSUE TITLE
As an ODH user I would like that station metadata (e.g. name) are available in multiple language

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#182]
This applies in particular for Bluetooth and LinkStations. All this should be mapped in the "metadata" table and made available through the Ninja API
Application is running in production. Once the spreadsheet metadata changes, the changes are reflected in the odh.
- [x] make bluetooth datacollector mutlilanguage able(https://mobility.api.opendatahub.bz.it/v2/flat/BluetoothStation/?limit=-1)
- [x] find a way to populate metadata of stations with no dc
- [ ] change host of bluetoothboxes due to migration from idm-dev-ds.eu-west-1.elasticbeanstalk.com -> boxes.opendatahub.bz.it

**Comment by bertolla** [comment]
For all Bluetooth stations you can already add name and description and whatever info you need through the spreadsheet. You can see it on the spreadsheet how it works. The trigger is currently manually but in production it will be triggered by changes in the spreadsheet.
@rcavaliere Can you insert some data so we can test?

**Comment by bertolla** [comment]
Changes after trigger can be seen here: https://mobility.api.opendatahub.testingmachine.eu/v2/tree/BluetoothStation/?limit=-1

**Comment by rcavaliere** [comment]
That's good, but what about other station types?

**Comment by bertolla** [comment]
There is multiple ways to achieve this. The question I pose myself is more like should we create something that enables you to do this for every stationtype or take the existing collector and add this functionality. Right now we just need it for `LinkStation` which don't have a datacollector pushing metadata.

**Comment by rcavaliere** [comment]
I have tested the first point, for me it is OK. I report here the decision with @Piiit and @bertolla for the second task: unique Spreadsheet with dedicated Data Collector for updating metadata in case of change. @bertolla will start implementing this Data Collector (can you create a separate user story?). @rcavaliere takes care of third task with CISMA

**Comment by rcavaliere** [comment]
Short update: CISMA has to make this change manually for each box, this will take a while... they will inform us about the time needed for that

**Comment by rcavaliere** [comment]
@bertolla is in contact with CISMA in order to test the new domain for delivering the Bluetooth data collected by the sensors. @bertolla: please provide a feedback to Elena Tomasi (see mail 28.01, 15:40)

**Comment by bertolla** [comment]
Done! Problem solved

**Comment by ohnewein** [comment]
Is "change host of bluetoothboxes due to migration from idm-dev-ds.eu-west-1.elasticbeanstalk.com -> boxes.opendatahub.bz.it" done?

**Comment by rcavaliere** [comment]
Not at the sensors level, @ohnewein. CISMA tested this and works, they need to fix this remotely on each sensor, and takes a little bit of time (also due COVID-19 limitations). Let's close this issue and please @bertolla keep alive both end-points for this migration period
