### ISSUE TITLE
dal/Measurement.java - dead code

### ISSUE THREAD

**Issue by mwallnoefer** [noi-techpark/bdp-core#188]
https://github.com/noi-techpark/bdp-core/blob/a6c8cc9be39c846aa3f2e0cf827ac36b8e2c4214/dal/src/main/java/it/bz/idm/bdp/dal/Measurement.java#L116

lines 116 and 117 are superfluous since a _Double_ matches also a _Number_. As an alternative the code could be swapped to gain the type optimisation without calling _doubleValue()_:
```
	@Override
	public void setValue(Object value) {
		if (value instanceof Double) {
			this.doubleValue = (Double) value;
		} else if (value instanceof Number) {
			this.doubleValue = ((Number) value).doubleValue();
		}
	}
```

**Comment by mwallnoefer** [comment]
Any news on this?

**Comment by bertolla** [comment]
Hi Matthias,
thanks for the input. We'll try to incorporate these changes in the next release.
Feel free to open a pull request, so that the changes are attributed to the right person.
In general we appreciate code contributions.

**Comment by mwallnoefer** [comment]
PR #198
