### ISSUE TITLE
dal/MeasurementStringHistory.java

### ISSUE THREAD

**Issue by mwallnoefer** [noi-techpark/bdp-core#189]
https://github.com/noi-techpark/bdp-core/blob/a6c8cc9be39c846aa3f2e0cf827ac36b8e2c4214/dal/src/main/java/it/bz/idm/bdp/dal/MeasurementStringHistory.java#L119

could better be converted into the following to avoid a potential null pointer dereference:
```
	@Override
	public void setValue(Object value) {
		if (value instanceof String)
			this.stringValue = (String) value;
	}
```

**Comment by mwallnoefer** [comment]
Any news on this?

**Comment by bertolla** [comment]
The null check should be done here for sure, but since every object implements the toString method we would like to avoid typechecking and prefer to keep it that way.
Thanks for your contribution

**Comment by mwallnoefer** [comment]
Ok, fine
