### ISSUE TITLE
As a traffic analyst I would like that the issue with the automatic ingestion / elaboration of A22 raw traffic data is solved

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#190]
We had a hole in December in the acquisition of traffic data from A22. This was already solved, but is still to be checked if everything works fine in the elaboration of the raw data.
Example: 
https://analytics.opendatahub.bz.it/#%7B%22active_tab%22:0,%22height%22:%22400px%22,%22auto_refresh%22:false,%22scale%22:%7B%22from%22:1606777200000,%22to%22:1609542000000%7D,%22graphs%22:%5B%7B%22category%22:%22Traffic%22,%22station%22:%22A22:679:2%22,%22station_name%22:%22SEZIONE%20DI%20RILEVAMENTO%20KM.%20%2087,8%20-%20BOLZANO%20SUD%20(corsia%20di%20sorpasso%20nord,%20direzione%20nord)%22,%22data_type%22:%22Average%20Speed%20Light%20Vehicles%22,%22unit%22:%22km/h%22,%22period%22:%22600%22,%22yaxis%22:1,%22color%22:3%7D%5D%7D

**Comment by bertolla** [comment]
Should be working now. Check the link you sent.
