### ISSUE TITLE
As a project manager I would like to have the Grafana views back visible on grafana.testingmachine.eu/

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#192]

**Comment by Piiit** [comment]
@rcavaliere I added you to the NOI Team, so you should have the permissions now. Could you please check

**Comment by rcavaliere** [comment]
@Piiit thanks! Yes I see something, but there is another view which I saw that is not visible anymore. If you provide me the entire list, I can say you which one it is.

**Comment by Piiit** [comment]
@rcavaliere I changed your permissions again... could you please re-test?

**Comment by rcavaliere** [comment]
@Piiit no, it's the same as before... @bertolla knows which are the right dashboards he prepared for me

**Comment by Piiit** [comment]
Strange, because you are admin now, you should see everything I guess

**Comment by bertolla** [comment]
You mean this: https://grafana.testingmachine.eu/d/fnfFHEZGz/mobility-collector-overview?orgId=1

**Comment by rcavaliere** [comment]
Yes @bertolla, exact!

**Comment by Piiit** [comment]
@bertolla @rcavaliere 

I moved you back to the viewer role, please check if you can still see everything you need.

**Comment by rcavaliere** [comment]
Yes, thanks
