### ISSUE TITLE
As a bike sharing data consumer I would like to see the bike sharing data of the service organized by the Municipality of Bolzano available as open data

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#194]
Please change the access rules to this dataset. This dataset has to be available for everyone!

**Comment by bertolla** [comment]
Sure, can do. Are all bikesharing data OpenData? Just asking because we have some specific rules there right now.

**Comment by rcavaliere** [comment]
yes, all bike sharing = open data
