### ISSUE TITLE
As a web component store manager I want to monitor the number of request to the Open Data Hub APIs coming from web components.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/bdp-core#245]
Priority: high
Deadline 4. March 2022

- [x] implement the referrer and origin parameter also in the mobility APIs
- [x] create a dashboard including the monitoring that includes both mobilty and tourism domain

https://docs.google.com/presentation/d/1EUonAlt0un8y3spGy9Db4o6pGcG_NDchKnoaQ_0ihI4/edit?usp=sharing

We follow the progress of `origin` enhanced calls in this list under the colum `webcomp check api calls and add origin`:
https://docs.google.com/spreadsheets/d/1T1kpA61oAouYV8TRWP3S8pPWW_aCX8xK-7G2Ip040jQ

**Comment by Piiit** [comment]
@sseppi Done... see https://logs.opendatahub.bz.it/app/dashboards#/view/73ddcc00-f802-11ea-b779-2f11d0d17b31

Now we need to add the origin parameters to the web component API calls

**Comment by Piiit** [comment]
Tested, it works, but we need to add all origin calls to the web components, and tell each website to use the latest version... see link for burndown document in main comment
