### ISSUE TITLE
As a project manager I would like to give Arxax the possibility to access A22 traffic data (closed dataset)

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#253]
Arxax has signed an agreement with A22 to access their traffic data through the ODH. The request is to set a new role that allows a user to just access the traffic data of A22 ("TrafficSensor")

**Comment by rcavaliere** [comment]
@dulvui @Piiit I would call the role "a22-trafficdata". The reference private dataset to be accessed is "TrafficSensor" (with origin = A22)

**Comment by dulvui** [comment]
The new role is named "BDP_A22_TRAFFICDATA" and is available now in testing environment

**Comment by rcavaliere** [comment]
@dulvui ok, can you put this in production?

**Comment by Piiit** [comment]
@rcavaliere @dulvui Ninja is online on production, just activate the new role on our production auth

**Comment by rcavaliere** [comment]
@Piiit thanks, I already did this. Let's make the customer test this

**Comment by Piiit** [comment]
OK, lets close it then and wait for feedback

**Comment by rcavaliere** [comment]
@Piiit @dulvui it seems that this currently does not work, see screenshot below. It seems to me that the user is correctly configured in KeyCloak. Can you check this?

![image](https://user-images.githubusercontent.com/9825179/173761135-c1e6578f-f000-46dd-b16d-64a17528a394.png)
![image1](https://user-images.githubusercontent.com/9825179/173761138-c30340de-f859-4363-8d52-0b664e612598.png)
![Screenshot from 2022-06-15 08-49-02](https://user-images.githubusercontent.com/9825179/173761195-8cc87502-30b9-4909-8590-febc7ff7679c.png)

**Comment by Piiit** [comment]
@rcavaliere I will have look...

**Comment by rcavaliere** [comment]
@Piiit did you already fix this? Because now Arxax has told me that it works... let's close the issue.

**Comment by Piiit** [comment]
@rcavaliere Yes fixed some parts, but I was still investigating the `Error! No data type available` problem in the screenshot... 

This problem has nothing to do with the login, also as "ADMIN" I see this error, maybe we just have a station here, but no associated types, nor measurements, could that be?

**Comment by Piiit** [comment]
OK, so it is fine to close this issue... maybe we should rephrase the "error" message in analytics and just say something like "This [-stationtype-] has no associated types or measurements"

**Comment by rcavaliere** [comment]
@Piiit yes, you are right!
