### ISSUE TITLE
As an Eurac Researcher I want that the weather data provided by the Sensor System Technologies Lab are integrated in the Open Data Hub, in order to be able to retrieve all data I need only by the Open Data Hub.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/bdp-core#254]
- [x] Gruppo FOS develops a data collector that takes the weather data provided by Eurac and stores it in the Open Data Hub (deadline end of June 2022) --> Dedicated Kanban: https://github.com/orgs/noi-techpark/projects/34
- [x] NOI checks if the existing data of some weather stations taken from SIAG are not simple duplicates of the new data collector
- [x] NOI integrates the new data collector in the ODH infrastructure

**Comment by Piiit** [comment]
@sseppi @rcavaliere 
Could you please provide more information about this issue?

**Comment by sseppi** [comment]
@Piiit till the end of June Gruppo FOS will develop a new data collector that takes the weather data provided by Eurac and stores it in the Open Data Hub.
Since we take already the data of some station also from SIAG, the most critical part would be to check that Gruppo FOS doesn't duplicate the stations and stores the data with the source at a measurement level.

**Comment by dulvui** [comment]
The dc is now running in testing environment with scheduled runs every 12 hours (at 12:00 and 24:00).
Tomorrow the data should be visible in the database.
Is this all open data? So I will make it publicly available trough Ninja API

**Comment by rcavaliere** [comment]
@dulvui nice! Yes, should be open data but let's wait that the open data contract with EURAC is signed first. This is followed by @sseppi. In the meantime, let' see if this DC puts down our testing infrastructure :-)

**Comment by rcavaliere** [comment]
@dulvui I have tested the DC, works perfectly as expected, very good! New measurements are appended to existing stations are requested, new stations are created correctly, existing types reused. Very good work by Gruppo FOS!
@sseppi is the contract with EURAC signed? So that we can release the data as open data when we go into production.

**Comment by sseppi** [comment]
Hi,
great news!
@rcavaliere no, at the moment the contract isn't signed. Since the reference person was on holiday. I will contact him again in order to speedup the process.

**Comment by rcavaliere** [comment]
@dulvui we can put the DC in production!

**Comment by dulvui** [comment]
The dc is now running on production.
The first data should be available after lunch, because the scheduled job runs at 12:00 and 24:00 o'clock
