### ISSUE TITLE
As a project manager I would like to have a role that allows to access all the data shared by A22

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#255]
This is needed in light of a new agreement between A22 and a new Data Consumer (Open Move)

**Comment by dulvui** [comment]
I will create a role BDP_A22 that shows all data with origin = 'A22' now on testing

**Comment by dulvui** [comment]
The role is now active in testing environment

**Comment by rcavaliere** [comment]
@dulvui super, seems to work. Can you put this in production?

**Comment by dulvui** [comment]
@rcavaliere Now it is available also in production.
