### ISSUE TITLE
Check rules about open / closed mobility datasets with new data collectors deployed

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#80]
- [x] update the broker spreadsheets @rcavaliere 
- [x] Write a list of rules, that define which measurements are visible for whom (also just in text form; no SQL) @rcavaliere 
- [x] Update the rules file inside bdp-core @Piiit 
- [x] Discuss about the feasibility of this approach to manually insert SQL statements vs. a webapp for ACL management

**Comment by rcavaliere** [comment]
@Piit @bertolla just deepened this.
I see that the APPATN open data is already correctly configured. One thing I don't understand is why we have double insertion for all roles for each of all this stations (station_id = 23950.....23957). Can you please explain this?
What we need to configure at the moment is the accessibility of APPABZ open data, but please we have to fix a bug related to the "active" status of some of these stations (see  https://github.com/idm-suedtirol/bdp-commons/issues/49). For some of them we need to go to period / type details, since we have a mix of open and closed data. How can I configure the table, shall I directly insert the rules in the DB or is there a better way to do this?

**Comment by Piiit** [comment]
@rcavaliere No, you need to modify the opendata sql rules. A file within bdp-core... However, you could just provide a list of which data must be visible for which role. So, I can write SQL rules. However, this is just a temporary solution... we should again discuss an ACL webapp for these tasks.
As for the duplicate entries, I will check about it, when I update the rules...

**Comment by rcavaliere** [comment]
I have summarized the current situation and associated rules in the attached file. Since the level of detail is higher (station, type, period) a new list has been necessary.
[190423_ODHRules.ods.zip](https://github.com/noi-techpark/bdp-core/files/3106143/190423_ODHRules.ods.zip)

**Comment by bertolla** [comment]
To test new opendatarules go to: http://tomcat.testingmachine.eu/analytics/
Do not forget that testdatabase only has data from mid april back.
I created multiple accounts which I will send @rcavaliere

**Comment by rcavaliere** [comment]
@bertolla tested it. 
In the testing environment some data flows are available only a couple of weeks in production (e.g. air quality stations by CBZ), so I can't test this properly in the testing environment since we don't have the updated situation. In general, the visibility of non-open data sources is in line with the new rules.
I suggest to put everything in production, if we then find some bugs we will fix it.

**Comment by Piiit** [comment]
@rcavaliere @bertolla I will make some last tests for all things on development and release the new core and commons version to our production environment...

**Comment by Piiit** [comment]
@rcavaliere Done. Please see if you get the right data with different users and without login on production
