### ISSUE TITLE
As a developer I want to have a nice JAVA-Doc for bdp-core so that I can easily understand the code and develop it further

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/bdp-core#82]
Java documentation following best practices(as good as possible) defined in https://www.oracle.com/technetwork/java/javase/tech/index-137868.html#styleguide and trying to document at least every public method.
These are the java modules to document:
- [x] dal
- [x] dto
- [x] dc-inteface
- [x] ws-interface
- [x] writer
- [x] reader

**Comment by ohnewein** [comment]
Looks as a very big improvement in documentation!

Some @return statements are empty, where I would consider the @return information the most important of all, because it usually describes very well what the method provides to the caller. 

I would suggest to always have @return and @param(s) documented. Having the @author(s) at class level is also important to know whom to ask for further help.

Overall a good job. For me it is OK.

**Comment by ohnewein** [comment]
A method documentation which could be improved:

/**
	 * @param stationType all datasets must have stations as reference with given stationtype
	 * @param responseLocation
	 * @param dataMap containing all data as measuerment in a tree structure
	 * @return correct response status code
	 */
	public static ResponseEntity<?> pushRecords(String stationType, URI responseLocation, DataMapDto<RecordDtoImpl> dataMap)

The @return doesn't provide me any insight about what this method will do. And there is no other description in the documentation. I do not know which status codes I can get, what do they mean?

Undocumented parameter: @param responseLocation


The same goes for the class itself:

/**
 * Writer API
 * @author Patrick Bertolla
 * @author Peter Moser
 *
 */
@Component
public class DataManager {

Being it a base class without interfaces I am kind of stuck to understand what this class is all about. The documentation just tells me it is a sort of "Writer API" which is not referenced nor documented. My only hope is to fund these authors (Patrick Bertolla and Peter Moser) and get some answers from them directly.

**Comment by Piiit** [comment]
@bertolla I did a review... please see comments inside each commit

**Comment by Piiit** [comment]
@bertolla @ohnewein Done. I skipped some classes, that I didn't understand fully and marked them as a TODO for Patrick B. :-) However, that is not that urgent...

**Comment by Piiit** [comment]
@bertolla @ohnewein Please test...
