### ISSUE TITLE
As a consumer of the ODH Mobility API, I want to get combined information faster and to use filters on data. Build a prototype to find a good technique

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-core#90]
- [x] Build a prototype with Postgrest to see, if it is feasible for a V2 API on web service's side
> PostgREST cannot deal sufficiently with view embedding (i.e., joins between views) and query rewrites across schemas.
> In addition, also row-level security as we implemented it, would not work anymore. We have to reimplement it with "real" row-level security, a Postgres build-in feature.
- [x] Since PostgREST is not an option, we need to invent a new API that reduces HTTP requests and adds filters, bounding-box and pagination features
> I tested with Hibernate, but with native queries, which do not have a good-enough performance
- [x] Since Hibernate with native queries is also no option, I try to build a prototype with JDBCTemplate (spring) and the Jsoniter JSON parser library

**UPDATE**

A first prototype (alpha) is ready and testable under http://tomcat.testingmachine.eu/reader2/api/v2/

Provide any number of station types first, and then any type of data types. (or `*` for "all")

For example,
- `http://tomcat.testingmachine.eu/reader2/api/v2/` gives all station types (categories)
- `http://tomcat.testingmachine.eu/reader2/api/v2/Meteostation/` gives only stations
- `http://tomcat.testingmachine.eu/reader2/api/v2/Meteostation/*` gives all datatypes of all meteo stations
- `http://tomcat.testingmachine.eu/reader2/api/v2/EChargingPlug,EChargingStation/echarging-plug-status,something,abc,xyz`

PARAMETERS:

- `select=mperiod,mvalue,tname,sname,sorigin`
- `limit=1000`  (default = 100)
- `offset=333` (default = 0)

**Comment by Piiit** [comment]
Some observations and ideas from our meeting (2019-04-21):

![photo_2019-04-09_10-27-18](https://user-images.githubusercontent.com/6096063/57688708-72f1a600-763e-11e9-8f0f-0fd94b86073c.jpg)

![photo_2019-04-09_10-27-21](https://user-images.githubusercontent.com/6096063/57688720-7ab14a80-763e-11e9-821d-713d3e5e989f.jpg)

**Comment by Piiit** [comment]
@bertolla @rcavaliere @RudiThoeni First v2 prototype ready. Please test... See comments above

**Comment by bertolla** [comment]
Tried to test but app is not reachable and gives proxy error

**Comment by bertolla** [comment]
This works really good, it's intuitive(for me) and you can create ouragious querries(like this: http://tomcat.testingmachine.eu/reader2/api/v2/*/mountain-bike-adult?select=sdatatypes&limit=5&offset=2).
For the next version sorting should be thought about.

**Comment by rcavaliere** [comment]
@Piiit I like the new API very much. It is much more flexible and I think for getting certain data it will be quicker, without the need to make multiple queries. User experience on the available beta apps will significantly improve. Wonderful!
