### ISSUE TITLE
As a consumer of the ODH Mobility API, I want to have a bounding box to fetch only stations that I need on a map

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-core#93]
- [x] Implement a bounding-box query to fetch stations within a region on a map
- [x] Add missing station, data type and measurement fields
- [x] Improve the Swagger API documentation
- [x] Add new syntax to the documentation
- [x] Add unit tests for the new functions
- [x] Update the test deployment pipeline to solely deploy "reader2"
- [x] Move swagger-ui.html to /

**Comment by Piiit** [comment]
@bertolla @rcavaliere Done, please test.

https://tomcatsec.testingmachine.eu/reader2

Documentation: https://github.com/noi-techpark/bdp-core/blob/readerv2/reader2/README.md

The new things are mostly filters:
- bbi: Bounding box intersecting objects (ex., a street that is only partially covered by the box)
- bbc: Bounding box containing objects (ex., a station or street, that is completely covered by the box)
- in: True, if the value of the alias can be found within the given list. Example: name.in.(Patrick,Rudi,Peter)
- and(alias.operator.value,...): Conjunction of filters (can be nested)
- or(alias.operator.value,...): Disjunction of filters (can be nested)

...and some special handling of empty or escaped values.

**Comment by bertolla** [comment]
A query which theoretically shouldn't work:
https://tomcatsec.testingmachine.eu/reader2/api/v2/hierarchy/MeteoStation?select=*&where=scoordinate.bbi.(11.213,46.9,12,47,4326).and(sname.in.(Ridanna))

For the rest it seems to be working fine.
