### ISSUE TITLE
As a consumer of the ODH Mobility API v2, I want to have a JSON filter and to select sub-sets of JSON

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-core#94]
- [x] Implement a JSON syntax to select only those sub-sets of JSON, that we really need as response (`SELECT`)
- [x] Implement a JSON syntax to filter stations according to their metadata (`WHERE`)
- [x] Allow <list> operators with JSONB, like `metadata.name.in.(Ana,Alex,Anton)`
- [x] Write and update the README + make some example queries
- [x] Write additional unit tests for jsonb select- and where-clause-expansions

**Comment by Piiit** [comment]
@bertolla @alexlanz This works now, I will also add some examples to the README now...

Example:

https://tomcatsec.testingmachine.eu/ninja/api/v2/flat/CreativeIndustry?limit=200&offset=0&select=smetadata.sector%2Csname%2Csmetadata.address&where=or(smetadata.sector.eq.Film%2Csmetadata.sector.eq.Musik)&shownull=false&distinct=true

**Comment by Piiit** [comment]
BUGS:
1) We have a duplicate with `"smetadata.state": null`.
http://tomcat.testingmachine.eu/ninja/api/v2/flat/EChargingStation?shownull=true&select=smetadata.state
gives
```
{
    "offset": 0,
    "data": [
        {
            "smetadata.state": null
        },
        {
            "smetadata.state": "TEMPORARYUNAVAILABLE"
        },
        {
            "smetadata.state": "UNKNOWN"
        },
        {
            "smetadata.state": "UNAVAILABLE"
        },
        {
            "smetadata.state": "AVAILABLE"
        },
        {
            "smetadata.state": "FAULT"
        },
        {
            "smetadata.state": "ACTIVE"
        },
        {
            "smetadata.state": "OCCUPIED"
        },
        {
            "smetadata.state": null
        },
        {
            "smetadata.state": "MAINTENANCE"
        }
    ],
    "limit": 200
}
```

2) We have an empty object and a `"smetadata.state": null`, although the shownull parameter is set to false.

http://tomcat.testingmachine.eu/ninja/api/v2/flat/EChargingStation?shownull=false&select=smetadata.state
gives
```
{
    "offset": 0,
    "data": [
        {},
        {
            "smetadata.state": "TEMPORARYUNAVAILABLE"
        },
        {
            "smetadata.state": "UNKNOWN"
        },
        {
            "smetadata.state": "UNAVAILABLE"
        },
        {
            "smetadata.state": "AVAILABLE"
        },
        {
            "smetadata.state": "FAULT"
        },
        {
            "smetadata.state": "ACTIVE"
        },
        {
            "smetadata.state": "OCCUPIED"
        },
        {
            "smetadata.state": null
        },
        {
            "smetadata.state": "MAINTENANCE"
        }
    ],
    "limit": 200
}
```

**Comment by Piiit** [comment]
@bertolla @rcavaliere Please test these new JSON select and where methods. Tell me, if it fixes the missing feature request in https://github.com/noi-techpark/odh-web-components/issues/9 too.
Example for testing can be found under the [Ninja README](https://github.com/noi-techpark/bdp-core/tree/development/ninja#sample-queries)

**Comment by bertolla** [comment]
I tested it and it covers all usecases for Belka, the only thing is that it does not support count yet but we can work around that. As soon as we are on production, I will change the querries for them.
I also tested it with NOI POI's and it worked correctly.

**Comment by Piiit** [comment]
@bertolla @rcavaliere Done. It is on production now!
